### ISSUE TITLE
AMP: Inductor fails with missing decomposition error

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#1001]
Repro
~~~
python benchmarks/torchbench.py --amp -dcuda --training --inductor --use-eval-mode --only=resnet50
~~~

~~~
  File "/scratch/anijain/work/pytorch/torch/fx/interpreter.py", line 162, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/scratch/anijain/work/torchdynamo/torchinductor/graph.py", line 216, in call_function
    raise MissingOperatorWithDecomp(target, args, kwargs)
torchinductor.exc.MissingOperatorWithDecomp: missing decomposition
  target: aten.t.default
  args[0]: TensorBox(StorageBox(
    ConstantBuffer(name='constant53', layout=FixedLayout('cuda', torch.float16, size=[1000, 2048], stride=[2048, 1]))
  ))

There is a decomposition available for aten.t.default in
torch._decomp.get_decompositions().  Please add this operator to the
`decompositions` list in `./torchinductor/decomposition.py`.

ERROR
missing decomposition
  target: aten.t.default
  args[0]: TensorBox(StorageBox(
    ConstantBuffer(name='constant53', layout=FixedLayout('cuda', torch.float16, size=[1000, 2048], stride=[2048, 1]))
  ))

There is a decomposition available for aten.t.default in
torch._decomp.get_decompositions().  Please add this operator to the
`decompositions` list in `./torchinductor/decomposition.py`.
~~~

**Comment by jansel** [comment]
I am not able to reproduce this from a PyTorch version from Aug 17 (0a48cdfb3bad14a62d9386ae0d1499bec74b63a6) so I think this is an upstream breakage in pytorch/aot_autograd.

We have a decomp for `aten.t`:
https://github.com/pytorch/torchdynamo/blob/424290a517ca254d2c422e9913d5f9ca292f2e47/torchinductor/decomposition.py#L82

Somehow it is not be applied due to some pytorch change in the past week.

**Comment by Chillee** [comment]
The fundamental problem here is that it seems like with amp, we're somehow converting weights into tensors that aren't tracked by `ProxyTensor`.

```
from functorch.compile import aot_module_simplified, print_compile
import torch

import torch
from torch.fx.experimental.proxy_tensor import make_fx

class Foo(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Conv2d(3, 3, 3)

    def forward(self, x):
        return (self.layer(x),)

with torch.cuda.amp.autocast():
    aot_module_simplified(Foo().cuda(), print_compile)(torch.randn(4, 3, 10, 10, device='cuda'))
```

![image](https://user-images.githubusercontent.com/6355099/186546225-35417af6-caaa-432e-8156-a02fc2c89741.png)

The more immediate error raised is that `aten.t.default` isn't decomposed, which is because when we call operators on non-tracked tensors, we don't decompose (https://github.com/pytorch/pytorch/blob/master/torch/fx/experimental/proxy_tensor.py#L398). I'm not sure this should ever happen though.

cc: @ezyang

**Comment by jansel** [comment]
If @ezyang doesn't know what the issue is maybe we need to `git bisect` on the pytorch repro.

**Comment by Chillee** [comment]
@jansel I know what commit is (probably) causing the issue (https://github.com/pytorch/pytorch/pull/83330), but that doesn't answer the cause.

Actually, I'm a bit suspicious that this has always been broken, and that the change just made it more obvious.

**Comment by Chillee** [comment]
Ok, I figured it out, with help from @eellison and @ngimel. Amp is caching dtype conversions on parameters (https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/autocast_mode.cpp#L130).

So, in AOTDispatcher, we run the function once to get the output shape, and then the second time we trace it.

So, we run it once, but then the second time, we load the value from cache (which shows up as a tensor constant).

**Comment by ngimel** [comment]
For everything except rnn disabling cache shouldn't matter much

**Comment by eellison** [comment]
Shouldn't we be able to recover caching via CSE anyway ?

**Comment by Chillee** [comment]
@eellison I think we can in many cases, but not if we graph break.

**Comment by Chillee** [comment]
https://github.com/pytorch/pytorch/pull/84035

This fixes it.

**Comment by ezyang** [comment]
@Chillee IMO we should also disable untracked tensors when make_fx is being run in a dynamo context, untracked tensors are ALWAYS a bug in this situation

**Comment by anijain2305** [comment]
Test passes now. Closing.
