### ISSUE TITLE
WONT CONVERT with fake tensors enabled on `shape_as_tensor(x)`

### ISSUE THREAD

**Issue by suo** [pytorch/torchdynamo#1030]
Extracted from a fairseq model: if `torchdynamo.config.fake_tensor_propagation = True`, then the following script
```
import torchdynamo
import torch.onnx.operators

def my_compiler(gm, inputs):
    return gm.forward

@torchdynamo.optimize(my_compiler)
def fn(x):
    return torch.onnx.operators.shape_as_tensor(x)

fn(torch.ones(2, 2))
```
leads to the following:
```
torchdynamo.convert_frame: [ERROR] WON'T CONVERT fn /private/home/suo/scratch/test.py line 9
due to:
Traceback (most recent call last):
  File "/raid/suo/pytorch/torch/onnx/operators.py", line 16, in shape_as_tensor
    return torch._shape_as_tensor(x)
RuntimeError: The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/raid/suo/torchdynamo/torchdynamo/variables/tensor.py", line 146, in create
    raise TorchRuntimeError() from e
torchdynamo.exc.TorchRuntimeError

from user code:
   File "/private/home/suo/scratch/test.py", line 11, in fn
    return torch.onnx.operators.shape_as_tensor(x)

Set torchdynamo.config.verbose=True for more information
==========
```

This is not a problem if fake tensors are off.

**Comment by suo** [comment]
@eellison are you the right person to look at this? https://github.com/pytorch/torchdynamo/issues/1062 seems similar?

**Comment by eellison** [comment]
Ugh, I think there are a few issues involved here.

- `_shape_as_tensor` is an ImplicitAutogradOp, so there is no current way to define a meta/fake impl for it. 
- We should have a better error for `The tensor has a non-zero number of elements, but its data is not allocated yet`, which means you're accessing `data_ptr` of FakeTensors.
- I would consider this an internal op, so we can add support for it, but we also need to define an API for registering an operator. I think decompositions are ideal here since they cover inductor / fake tensors / sym ints. Python Meta impl's kind of work but they dont by themself cover non-standard device rules or inductor.
- For this particular op, I'm not sure how well it will work out of the gate since you probably want to actually have constant or symbolic values for the output. 

thoughts @ezyang ?

**Comment by bdhirsh** [comment]
I think `_shape_as_tensor` is not composite compliant, and we should make it a primitive (by making it `CompositeExplicitAutograd`).

It doesn't look like it's composite compliant, because it calls the `at:tensor()` [constructor](https://github.com/pytorch/pytorch/blob/d144594512e10ab2a9625347816c2dee1fb55667/aten/src/ATen/native/TensorShape.cpp#L183). `at::tensor()` constructs an empty tensor and [tries to poke at the data pointer](https://github.com/pytorch/pytorch/blob/d144594512e10ab2a9625347816c2dee1fb55667/aten/src/ATen/Utils.cpp#L28) of the output (which might be a tensor subclass)

**Comment by ezyang** [comment]
Agreed with @bdhirsh's diagnosis. Derivative formula should not be necessary; the returned tensor is a LongTensor anyway.

**Comment by Chillee** [comment]
I don't think we should make it a primitive.

For symbolic shape purposes, this op is a non-starter. 

I think we should just intercept in torchdynamo.

**Comment by bdhirsh** [comment]
Oh I ended up making a fix here (I can hold off on landing): https://github.com/pytorch/pytorch/pull/84868

Hmmm @Chillee, can you elaborate? Right now, the decomposition basically just results in garbage. So anyone who isn't using the dynamo stack that runs this op would probably still run into trouble (XLA tensors, or basically using a tensor subclass that doesn't have valid storage).

**Comment by bdhirsh** [comment]
Attempting to summarize offline conversation with @Chillee 

This PR might be insufficient for two reasons:

(1) presumably if you're storing a shape inside of a tensor, there is probably some code later that calls `.item()` on it to grab the shape and create a tensor of that shape. If we make `_shape_as_tensor` a primitive, then that tensor shape becomes dynamic tensor data, and mobile's tracer would choke on the `.item()` call.

So we probably want `_shape_as_tensor(x)` to decompose into something like `torch.tensor(x.shape)` instead.

(2) If `x` has a dynamic (or changing) shape in your model though, then the above isn't enough - doing (1) will bake `x.shape` as a constant into the graph, when what we really want to bake into the graph is something like `tensor_constructor(x.shape)`.

It makes sense to me that (2) will require support from dynamo, because ATen IR doesn't actually have a way to represent the tensor constructor `torch.tensor(x.shape)`. I guess one option would be adding a version of the `torch.tensor()` constructor as an ATen op that specializes on 1D lists (instead of arbitrary python lists), but fixing the problem with dynamo feels easier (for one, we'd need to make a new aten op and wait for the 2 week FC window to pass).


I still think that "making `_shape_as_tensor()` a primitive in ATen is worth landing (since the decomp today just seems bad), but it probably isn't enough to fix the issue for mobile.

@mengwa41 @zhxchen17 Do you happen to know if the model using `_shape_as_tensor()` e.g. is followed by a `.item()` call, or if the shape of the passed-in-tensor is changing?

**Comment by zhxchen17** [comment]
> Attempting to summarize offline conversation with @Chillee
> 
> [This fix](https://github.com/pytorch/pytorch/pull/84868) might be insufficient for two reasons:
> 
> (1) presumably if you're storing a shape inside of a tensor, there is probably some code later that calls `.item()` on it to grab the shape and create a tensor of that shape. If we make `_shape_as_tensor` a primitive, then that tensor shape becomes dynamic tensor data, and mobile's tracer would choke on the `.item()` call.
> 
> So we probably want `_shape_as_tensor(x)` to decompose into something like `torch.tensor(x.shape)` instead.
> 
> (2) If `x` has a dynamic (or changing) shape in your model though, then the above isn't enough - doing (1) will bake `x.shape` as a constant into the graph, when what we really want to bake into the graph is something like `tensor_constructor(x.shape)`.
> 
> It makes sense to me that (2) will require support from dynamo, because ATen IR doesn't actually have a way to represent the tensor constructor `torch.tensor(x.shape)`. I guess one option would be adding a version of the `torch.tensor()` constructor as an ATen op that specializes on 1D lists (instead of arbitrary python lists), but fixing the problem with dynamo feels easier (for one, we'd need to make a new aten op and wait for the 2 week FC window to pass).
> 
> I still think that "making `_shape_as_tensor()` a primitive in ATen is worth landing (since the decomp today just seems bad), but it probably isn't enough to fix the issue for mobile.
> 
> @mengwa41 @zhxchen17 Do you happen to know if the model using `_shape_as_tensor()` e.g. is followed by a `.item()` call, or if the shape of the passed-in-tensor is changing?
cc @suo who knows better about the model behavior.

**Comment by ezyang** [comment]
Can't we do the same trick we're doing for wrapped numbers? The produced tensor has a special private attribute saying how you can recover the SymInts that went into it, and if you item() call from Python, you use those attributes to work it out.

**Comment by suo** [comment]
@bdhirsh the way it's used is basically:
```
x = _shape_as_tensor(foo)
foo, bar = x[0], x[1]
```
with static shapes, so rewriting the `_shape_as_tensor` call as a `size()` call works fine. The purpose of `_shape_as_tensor` is generally to make ONNX tracing work.

Here's an example PR I put up manually rewriting this pattern: https://github.com/facebookresearch/fairseq/pull/4708

**Comment by tugsbayasgalan** [comment]
If no has worked on intercepting _shape_as_tensor(x) as x.shape, I would like to work on it

**Comment by tugsbayasgalan** [comment]
If no one worked on it yet, I will try to do this in dynamo by intercepting _shape_as_tensor and replace that with shape
