### ISSUE TITLE
We should not be monkey patching CODE onto logging module

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#1932]
### 🐛 Describe the bug

The logging module is part of Python builtin modules. CODE is a very generic name. We could easily be clobbering / be clobbered by someone else monkey patching this module. This is not polite library code.

**Comment by mlazos** [comment]
Hmm, this is pretty standard practice if you're adding a log level. We could check if the name already exists and throw if it does before patching? cc @williamwen42

**Comment by ezyang** [comment]
The distinction is an application vs a library. A library needs to work in a variety of contexts, and good citizenship means not making precommitments in global namespaces (like logging.CODE) when other apps may want to choose differently.

**Comment by williamwen42** [comment]
My old suggestion to avoid the use of logging.CODE is to stuff it into INFO, but have an additional flag in config to control old CODE output. i.e. `log.log(logging.CODE, "stuff")` becomes
```
if torch._dynamo.config.log_code:
    log.info("stuff")
```

**Comment by mlazos** [comment]
I see two alternatives: 
William's suggestion above, or aliasing all of the levels under a separate namespace like torch._dynamo.logging.CODE, torch._dynamo.logging.INFO = logging.INFO, etc. 

The reason I prefer not to have a separate flag is that we can filter different logging events based on the level, just because we aren't sending it to the console doesn't mean it shouldn't be sent to a file etc. This allows us to have a debug log available as a file without spamming the console.
