### ISSUE TITLE
how to get the path of the generated triton codes (triton code and its generated IRs)?

### ISSUE THREAD

**Issue by stephen-youn** [pytorch/torchdynamo#2007]
### 🐛 Describe the bug

Hi,
in [this ](https://pytorch.org/blog/Accelerating-Hugging-Face-and-TIMM-models/)blog tutorial and several threads in this git repo, it seems a path to the temporary triton files should be given if I run the torchinductor with TORCHINDUCTOR_TRACE set to 1.
it seems it's generated under /tmp/torchinductor_"my-id"
but there are too many files and it's hard to tell which files are generated after the executing the example.

```
env TORCHINDUCTOR_TRACE=1 python hello_torchdynamo.py
```

however, it seems it used to print out a warning line with the path to the generated triton codes if it's given "TORCHINDUCTOR_TRACE=1" ahead.
how can i print out the path after executing the line above?
right now, if i just follow the steps in the blog post(with the correction to give input_tensor as argument  to new_fn in toy example), it prints out nothing but executing things silently
let me know how to get the path of the generated triton codes with "TORCHINDUCTOR_TRACE=1"
thanks

### Minified repro

"""
hello_torchdynamo.py
"""
~~~
import torch
def fn(x, y):
    a = torch.sin(x).cuda()
    b = torch.sin(y).cuda()
    return a + b
new_fn = torch.compile(fn, backend="inductor")
input_tensor = torch.randn(256).to(device="cuda:0")
a = new_fn(input_tensor, input_tensor)

~~~

In the command line, run the following command
~~~
~/project/sandbox$ env TORCHINDUCTOR_TRACE=1 python hello_torchdynamo.py
~~~
- nothing printed out but expected the path to the torchinductor trace would be given

**Comment by anijain2305** [comment]
@stephen-youn Thanks for trying out `torch.compile`. There are a couple of issues on our end here
* TORCHINDUCTOR_TRACE flag is deprecated. We now use `TORCH_COMPILE_DEBUG=1`. With this, you will see more verbose logging. For inductor related kernels, you can search for `torch._inductor.debug`. Thanks for pointing this inconsistency in the tutorial. I will fix it.
* You are right that Inductor generates a lot of file inside /tmp/torchinductor_username. Many of these are individual fused Triton kernels generated by Inductor. Instead of looking at the /tmp folder, I would suggest to look at the TORCH_COMPILE_DEBUG log. For example, for your code, I see this line 

~~~
[2022-12-30 00:21:28,218] torch._inductor.debug: [WARNING] model__0_inference_0 debug trace: /scratch/anijain/work/pytorch/torch_compile_debug/run_2022_12_30_00_21_26_392977/aot_torchinductor/model__0_inference_0.0
~~~

And when I enter into the above folder, I can see `output_code.py`. This points to the Inductor generated fused kernels for the entire subgraph and how these kernels are called. You can even run this `output_code.py` file.

**Comment by anijain2305** [comment]
@msaroufim Can you please update the blog https://pytorch.org/blog/Accelerating-Hugging-Face-and-TIMM-models/ to reflect the name change from TORCHINDUCTOR_TRACE to TORCH_COMPILE_DEBUG. Or let me know how to update it, I cant find the source file.
