### ISSUE TITLE
3% Memory Regression when Compiling the Optimizer 

### ISSUE THREAD

**Issue by eellison** [pytorch/torchdynamo#2033]
### 🐛 Describe the bug

[Compiling the optimizer](https://github.com/pytorch/pytorch/pull/90709) introduced a ~3% memory regression as observed in the performance dashboard. @mlazos, @ngimel and others have tried debugging a bit but we haven't yet found the culprit.

3% is not huge but it's still worth getting to the bottom of this, and memory overheads add up.

**Comment by mlazos** [comment]
The [CheckFunctionManager](https://github.com/pytorch/pytorch/blob/933cc67e7ebbdfb8bf5b1b20309166b0eb2952a7/torch/_dynamo/guards.py#L493) contains a circular reference to itself, which keeps the output_graph alive. Within the output_graph the side_effects tracker would keep the grads from all of the parameters of the model in its keepalive list (to track mutation of the list containing all of the grads) which is necessary during analysis, but should be released once we've generated code. This was only noticeable after compiling the optimizer because the grads for the entire model were kept in a list, but this may help memory across a lot of models if tensors were stored in containers which could be mutated. I'm removing the full output graph from the CheckFunctionManager, and this should allow side_effects to get cleaned up after compilation.

**Comment by mlazos** [comment]
benchmark to repro https://gist.github.com/mlazos/7969081049d4e0681774defc0d0f50c7
