### ISSUE TITLE
dtype info lost during tensor -> numpy -> tensor conversion

### ISSUE THREAD

**Issue by yanboliang** [pytorch/torchdynamo#292]
*This is the 7/N issue found from https://github.com/pytorch/torchdynamo/issues/156.*

Minimal code to reproduce:
```
from typing import List
import torch
import torchdynamo

def fn(x):
    x_np = x.numpy()
    weight = []
    z = x_np[0] / 20
    weight.append(z)
    return torch.tensor(weight)

def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    return gm.forward

x = torch.ones([1], dtype=torch.int64)
with torchdynamo.optimize(my_compiler):
    print(fn(x).dtype)
```
The output is ```torch.float32```, however, it's ```torch.float64``` on pytorch.

I'm working this issue and found ```x_np[0]``` is python ```float``` rather than ```numpy.float64```, so sth wrong happens before that. Want to check if anyone has encountered similar issue or have any thought? @jansel

**Comment by jansel** [comment]
I tink this issue is coming from here:
https://github.com/pytorch/torchdynamo/blob/77b561823b4a0330cc7db2f68292c16735b6d694/torchdynamo/variables/builder.py#L286

Where we convert it to an int and specialize on it.

A related issue is: https://github.com/pytorch/torchdynamo/issues/70 
Which this example will also suffer from by over-specializing on the value of `x_np[0]`.
