### ISSUE TITLE
torchdynamo minifier

### ISSUE THREAD

**Issue by mlazos** [pytorch/torchdynamo#897]
Implement a record-replay tool which dumps the instructions/environment needed for running the exact frame where an error occurred and produce this debug file on error

**Comment by voznesenskym** [comment]
Hmmm one major difference between dynamo and inductor is that inductor produces a compiled kernel. Because the input is an fx graph, it can then minify the graph to produce that, using the fx_minifier. For us, the breadth of valid input is far greater (all python?) Do you plan to make something that operates on raw python code? 

A potential alternative might be less of a minifier and more of an extractor. Where a minifier starts with the full graph and cuts it down, perhaps we can instead fetch the current frame we failed on, and try to generate a wrapper for calling the closest-highest-up func with dummy data (produced from looking at tensor/type medata). What do you think?

**Comment by Chillee** [comment]
One additional benefit of the minifier is that it produces an artifact that we can use to reproduce the error without needing to set up their environment.

**Comment by mlazos** [comment]
I built a prototype on wed, the idea is that it records the instructions that are traced and vars that are accessed in the most recently run frame, and on error packages them up into a file. I added another front end to dynamo that opens the file and reruns the code. The key part is to only record the vars and instructions that are accessed, so then you don't need the entire env/modules. 

For v0, I'm not going to handle modules, so it would only work if you have the same modules in the global env as when you ran it. This would be useful for individual devs who just want to run the frame where an error occurred on the same machine where the recording was done.

For v1, I want this to be usable across machines. My strategy here is to introduce dummy vars that only have the module attributes that have been used in the instructions recorded so far.
