### ISSUE TITLE
PyTorch-CI Blocker - Unspec fails with randrange with while loop

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#982]
Repro - This leads to an infinite loop
~~~
import torch
import torchdynamo
import random

import logging

torchdynamo.config.log_level = logging.DEBUG

SIZE = 4
device = "cpu"

def fn(x):
    dim1 = random.randrange(start=0, stop=3)
    dim2 = dim1
    while dim1 == dim2:
        dim2 = random.randrange(start=0, stop=3)
    return x * 2

x = torch.randn(4)
fn(x)
print("DONE", flush=True)
opt_fn = torchdynamo.optimize("eager")(fn)
opt_fn(torch.randn(4))
~~~

This is because we hack the random values like this
https://github.com/pytorch/torchdynamo/blob/7f6fbdf27c0e200d142525782b102e98da5b6acb/torchdynamo/variables/user_defined.py#L145-L155

@yanboliang  This seems like an incorrect impl. Shouldn't we graph break on random?

cc @ezyang for PyTorch CI visibility.

**Comment by yanboliang** [comment]
> Shouldn't we graph break on random?

I think we should't break on random if we can. In most cases, random output would be easily inserted into the graph and we can generate a larger graph. E.g,
```
m = torch.nn.ReLU()
x = torch.randn(shape, device="cpu") * random.randint(30, 100)
y = m(x)
``` 

For this case, it fails because we always use the same ```example_value``` for this unspec variable. So if there are multiple random calls, actually they generate same ```example_value``` during compile and cause the infinite loop. I think the fix is to make multiple random calls generate different ```example_value```(fake random) during compile. I'll send a PR to fix this tomorrow.
